### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by kdrypr** [WuerthPhoenix/log_generator#1]
`Traceback (most recent call last):
  File "/usr/local/bin/rlog-generator", line 6, in <module>
    from rlog_generator.cli import main
  File "/usr/local/lib/python2.7/dist-packages/rlog_generator/cli.py", line 74
    print(f"\nGenerated {total_logs} logs")
                                         ^
SyntaxError: invalid syntax`

I got this error while running the script. I installed with pip install rlog-generator and got no error message.

**Comment by fedelemantuano** [comment]
Hi @kdrypr,

you are using python 2.7, that it's deprecated.
This tool works from Python 3.6.
